### ISSUE TITLE
Can we add support for vPilot 3.11.0 - Released 12/10/24

### ISSUE THREAD

**Issue by martyp187** [renorris/vpilot-patch-utility#1]
Latest Stable Version: 3.11.0 - Released 12/10/24

I did try and change the hash and patch this version, but upon opening vPilot.exe I get a .net error and then none of the interface of vPilot worked.

**Comment by renorris** [comment]
Done https://github.com/renorris/vpilot-patch-utility/commit/1b2d9ed4cbdd8d1e53c54d1a724bd2abfca13c5b

**Comment by martyp187** [comment]
In that case, it wasn't the hash that was the issue.

The patch builds and applies successfully now to 3.11.0 but the .net error still comes up when vPilot starts.

As a test, I left the patched vPilot as it was, but swapped it back in the original vPilotConfig.xml.

With the original file in place, vPilot opens with no .net error.

Let me know if I can help any more!

**Comment by renorris** [comment]
Interesting, is there any specific message or stacktrace in the .NET error?

**Comment by renorris** [comment]
I've pushed a fix that may help in certain cases where installing a new version of vPilot "desynchronizes" the patcher, leading to weird bugs. Try it out and let me know. Doing a full reinstall of vPilot would also be prudent. Also check your `C:\Users\YourUsername\AppData\Local\vPilot` directory, and delete any files ending in `.orig` (although this should be unnecessary with the fix I initially mentioned.)

**Comment by martyp187** [comment]
Ok, so I did a few tests.

If I make a new patch, and apply it to a fresh install, I get the a .net error when opening vPilot.

If I create a patch, with the vanilla patchfile.yml, and apply it, vPilot does open.

If I make a change to the patch file (uncomment the two example cached servers at the bottom), make a new patch and apply it, the .net error is back.

**Could it be any server address/domain name that ends in a 404 error that would cause this?**

![Image](https://github.com/user-attachments/assets/1498c0e7-0e8e-4f05-a6cc-57862bcb5f89)

The details box contains the below:

`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at dp.ag()
   at df.a(Object A_0, f5 A_1)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9290.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
vPilot
    Assembly Version: 3.11.0.0
    Win32 Version: 3.11.0.0
    CodeBase: file:///C:/Users/marty/AppData/Local/vPilotVATSIM/vPilot.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9256.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
Serilog
    Assembly Version: 2.0.0.0
    Win32 Version: 2.10.0.0
    CodeBase: file:///C:/Users/marty/AppData/Local/vPilotVATSIM/Serilog.DLL
----------------------------------------
Serilog.Sinks.File
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.0.0
    CodeBase: file:///C:/Users/marty/AppData/Local/vPilotVATSIM/Serilog.Sinks.File.DLL
----------------------------------------
Ninject
    Assembly Version: 3.2.0.0
    Win32 Version: 3.2.2.0
    CodeBase: file:///C:/Users/marty/AppData/Local/vPilotVATSIM/Ninject.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9297.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9282.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Ninject.Extensions.Factory
    Assembly Version: 3.2.0.0
    Win32 Version: 3.2.1.0
    CodeBase: file:///C:/Users/marty/AppData/Local/vPilotVATSIM/Ninject.Extensions.Factory.DLL
----------------------------------------
Castle.Core
    Assembly Version: 3.2.0.0
    Win32 Version: 3.2.0.2259
    CodeBase: file:///C:/Users/marty/AppData/Local/vPilotVATSIM/Castle.Core.DLL
----------------------------------------
bbv.Common.EventBroker
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Users/marty/AppData/Local/vPilotVATSIM/bbv.Common.EventBroker.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
DynamicProxyGenAssembly2
    Assembly Version: 0.0.0.0
    Win32 Version: 3.2.0.2259
    CodeBase: file:///C:/Users/marty/AppData/Local/vPilotVATSIM/Castle.Core.dll
----------------------------------------
DynamicProxyGenAssembly2
    Assembly Version: 0.0.0.0
    Win32 Version: 3.2.0.2259
    CodeBase: file:///C:/Users/marty/AppData/Local/vPilotVATSIM/Castle.Core.dll
----------------------------------------
abacus
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Users/marty/AppData/Local/vPilotVATSIM/abacus.DLL
----------------------------------------
RossCarlson.Vatsim.Vpilot.Plugins
    Assembly Version: 3.11.0.0
    Win32 Version: 3.11.0.0
    CodeBase: file:///C:/Users/marty/AppData/Local/vPilotVATSIM/RossCarlson.Vatsim.Vpilot.Plugins.DLL
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.9290.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
protobuf-net
    Assembly Version: 2.0.0.668
    Win32 Version: 2.0.0.668
    CodeBase: file:///C:/Users/marty/AppData/Local/vPilotVATSIM/protobuf-net.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
CoreCompat.Portable.Licensing
    Assembly Version: 1.2.0.0
    Win32 Version: 1.2.14.52145
    CodeBase: file:///C:/Users/marty/AppData/Local/vPilotVATSIM/CoreCompat.Portable.Licensing.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
log4net
    Assembly Version: 1.2.10.0
    Win32 Version: 1.2.10.0
    CodeBase: file:///C:/Users/marty/AppData/Local/vPilotVATSIM/log4net.DLL
----------------------------------------
Microsoft.FlightSimulator.SimConnect
    Assembly Version: 10.0.61259.0
    Win32 Version: 10.0.61637.0 (FSX-Xpack.20070926-1421)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_32/Microsoft.FlightSimulator.SimConnect/10.0.61259.0__31bf3856ad364e35/Microsoft.FlightSimulator.SimConnect.dll
----------------------------------------
msvcm80
    Assembly Version: 8.0.50727.9680
    Win32 Version: 8.00.50727.9680
    CodeBase: file:///C:/WINDOWS/WinSxS/x86_microsoft.vc80.crt_1fc8b3b9a1e18e3b_8.0.50727.9680_none_d090cb7c44278b28/msvcm80.dll
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
SharpDX.DirectInput
    Assembly Version: 2.6.3.0
    Win32 Version: 2.6.3
    CodeBase: file:///C:/Users/marty/AppData/Local/vPilotVATSIM/SharpDX.DirectInput.DLL
----------------------------------------
SharpDX
    Assembly Version: 2.6.3.0
    Win32 Version: 2.6.3
    CodeBase: file:///C:/Users/marty/AppData/Local/vPilotVATSIM/SharpDX.DLL
----------------------------------------
GeoVR.Shared
    Assembly Version: 2.2.0.0
    Win32 Version: 2.2.0.0
    CodeBase: file:///C:/Users/marty/AppData/Local/vPilotVATSIM/GeoVR.Shared.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.9032.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
GeoVR.Client
    Assembly Version: 2.2.0.0
    Win32 Version: 2.2.0.0
    CodeBase: file:///C:/Users/marty/AppData/Local/vPilotVATSIM/GeoVR.Client.DLL
----------------------------------------
GeoVR.Connection
    Assembly Version: 2.2.0.0
    Win32 Version: 2.2.0.0
    CodeBase: file:///C:/Users/marty/AppData/Local/vPilotVATSIM/GeoVR.Connection.DLL
----------------------------------------
NLog
    Assembly Version: 4.0.0.0
    Win32 Version: 2.2.0.0
    CodeBase: file:///C:/Users/marty/AppData/Local/vPilotVATSIM/GeoVR.Client.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.


`

**Comment by renorris** [comment]
Thanks a ton for all the information. It seems like I overlooked a critical detail in order to format the cached servers—you'll need to delimit the server name and the address with a `|` character.

https://github.com/renorris/vpilot-patch-utility/blob/88573499f0bbf66e8b6808dd9518485a558845e0/patchfile.yml#L62-L65

**Comment by martyp187** [comment]
That fixed it, thanks!

Can you confirm for me that vPilot must connect to the custom fsd-jwt URL via https. This is not optional?

**Comment by renorris** [comment]
Yeah, vPilot is hardcoded to obtain an auth token from fsd-jwt before presenting it to the FSD server.

Eventually I could take a look and see if it could be patched to present the plaintext password instead. Which FSD server software are you attempting to use?

**Comment by martyp187** [comment]
Trying to run openfsd (via Docker Compose), which works, until I specify a path to a .crt and .key file to enable tls, then it just loops on startup.
